spring:
    application:
        name: jobertyService 
    data:
        mongodb: 
            authentication-database: admin 
            username: root 
            password: example 
            database: dislinkt
            host: mongo
            port: 27017 
server:
    port: 8089