spring:
    application:
        name: postService 
    data:
        mongodb: 
            authentication-database: admin 
            username: root 
            password: example 
            database: dislinkt
            host: localhost 
            port: 27017 
server:
    port: 8081